language: node_js
sudo: required
addons:
    chrome: stable
node_js:
- 8
os: linux
cache:
  yarn: true
branches:
  only:
  - master
  - develop
install:
- |
    yarn install
script:
- |
    npm run lint && npm run test
after_success:
- |
    cat ./test/coverage/lcov.info | ./node_modules/.bin/codecov